services:
  - type: web
    name: eventlife-backend
    env: node
    plan: free
    buildCommand: cd Backend && npm install && npm run build
    startCommand: cd Backend && npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /health

